-- create table activityuserdetail (
--     id int,
--     firstname varchar(255),
--     lastname varchar(255),
--     username varchar(255),
--     email varchar(255),
--     password varchar(255)
-- );

-- insert into activityuserdetail (id,firstname,lastname,username,email,password) values (1,'a','a','a','a','a');
-- insert into activityuserdetail (id,firstname,lastname,username,email,password) values (2,'b','b','b','b','b');
-- insert into activityuserdetail (id,firstname,lastname,username,email,password) values (3,'c','c','c','c','c');
-- insert into activityuserdetail (id,firstname,lastname,username,email,password) values (4,'d','d','d','d','d');